export enum FieldTypes {
  TEXT = "TEXT",
  NUMBER = "NUMBER",
  IMAGES = "IMAGES",
  CHECKBOX = "CHECKBOX",
  RADIO_OPTIONS = "RADIO_OPTIONS",
  DROPDOWN = "DROPDOWN",
  DATE = "DATE",
  LARGE_TEXT = "LARGE_TEXT",
}
